version: "3.8"

services:
  # Redis 服务
  redis:
    image: redis:latest
    container_name: wam-business-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - wam-business

  # mysql 数据库服务
  mysql:
    image: mysql:lts
    container_name: wam-business-mysql
    restart: always
    security_opt:
      - seccomp:unconfined
    command: mysqld --mysql-native-password=ON --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/config:/etc/mysql/conf.d
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    environment:
      SET_CONTAINER_TIMEZONE: "true"
      CONTAINER_TIMEZONE: "Asia/Shanghai"
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_ROOT_HOST: "%"  # Allow connections from any host
    networks:
      - wam-business

networks:
  wam-business: