version: "3.8"

services:
  # Redis 服务
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
  # mysql 数据库服务
  mysql:
    image: mysql/mysql-server:latest
    restart: always
    security_opt:
      - seccomp:unconfined
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ${PWD}/mysql/data:/var/lib/mysql
      - ${PWD}/mysql/config:/etc/mysql/conf.d
    ports:
      - 3306:3306
    environment:
      SET_CONTAINER_TIMEZONE: "true"
      CONTAINER_TIMEZONE: "Asia/Shanghai"
      MYSQL_ROOT_PASSWORD: "123456"