// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/ai/predict/forwardDirection": {
            "post": {
                "description": "提供配方信息并进行预测，返回实验结果的预测值",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模型预测"
                ],
                "summary": "根据配方信息预测实验结果",
                "parameters": [
                    {
                        "description": "配方预测请求参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ai.ForwardDirectionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "预测成功，返回预测的实验结果",
                        "schema": {
                            "$ref": "#/definitions/ai.ForwardDirectionResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误，可能是配方信息不完整或格式不正确",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误，可能是预测服务异常",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/changPassword": {
            "put": {
                "description": "根据提供的原密码及新密码等信息修改用户当前账户的密码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户认证"
                ],
                "summary": "修改用户密码",
                "parameters": [
                    {
                        "description": "请求参数，包含原密码、新密码等修改密码所需信息",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.ChangePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功修改密码，返回空对象表示操作成功",
                        "schema": {
                            "$ref": "#/definitions/dto.Empty"
                        }
                    },
                    "201": {
                        "description": "可根据实际情况设置不同成功状态码及对应含义，这里示例201可表示密码已成功更新并生效",
                        "schema": {
                            "$ref": "#/definitions/dto.Empty"
                        }
                    },
                    "400": {
                        "description": "请求参数错误，如原密码错误、新密码格式不符合要求等",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误，可能是数据库更新出错、验证逻辑异常等情况",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/data/experiment": {
            "get": {
                "description": "根据分页请求获取实验列表，支持按实验名称进行筛选",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "实验管理"
                ],
                "summary": "获取实验列表",
                "parameters": [
                    {
                        "description": "请求参数，包含分页信息及筛选条件",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/data.ExperimentListRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功获取实验列表，返回实验数据",
                        "schema": {
                            "$ref": "#/definitions/data.ExperimentListResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误，如分页参数错误、筛选条件不符合要求",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误，可能是数据库查询出错等情况",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "根据实验ID删除实验",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "实验管理"
                ],
                "summary": "删除实验",
                "parameters": [
                    {
                        "description": "请求参数，包含要删除的实验ID",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/data.ExperimentDeleteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功删除实验",
                        "schema": {
                            "$ref": "#/definitions/dto.Empty"
                        }
                    },
                    "400": {
                        "description": "请求参数错误，如实验ID不存在或格式无效",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误，可能是数据库删除失败等情况",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/data/experiment/info": {
            "get": {
                "description": "根据实验ID获取实验的详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "实验管理"
                ],
                "summary": "获取指定实验的详情信息",
                "parameters": [
                    {
                        "description": "请求参数，包含实验ID",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/data.ExperimentInfoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回实验详情",
                        "schema": {
                            "$ref": "#/definitions/data.ExperimentInfoResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误，如实验ID不存在或格式无效",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误，可能是查询失败等情况",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/data/task": {
            "get": {
                "description": "支持分页查询任务列表，可按任务名称筛选",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务管理"
                ],
                "summary": "获取任务列表",
                "parameters": [
                    {
                        "description": "分页参数及筛选条件",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/data.TaskListRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回任务列表",
                        "schema": {
                            "$ref": "#/definitions/data.TaskListResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误，如分页参数错误、筛选条件不符合要求",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误，可能是数据库查询失败",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "接收并存储上传的任务文件，支持多文件上传，限制最大 100MB/文件，最多 20 个文件",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务管理"
                ],
                "summary": "上传任务文件",
                "parameters": [
                    {
                        "type": "file",
                        "description": "上传的文件，支持多个",
                        "name": "files",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "文件上传成功",
                        "schema": {
                            "$ref": "#/definitions/dto.Empty"
                        }
                    },
                    "400": {
                        "description": "请求参数错误，可能是文件上传失败或格式不符合要求",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误，可能是文件解析或存储失败",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "提供用户名和密码进行登录操作，验证用户身份并获取相应权限",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户认证"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "请求参数，包含用户名、密码等登录所需信息",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功登录，返回token凭证表示操作成功",
                        "schema": {
                            "$ref": "#/definitions/auth.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误，如用户名或密码格式不正确等",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误，可能是数据库查询出错、验证逻辑异常等情况",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "ai.ForwardDirectionRequest": {
            "type": "object",
            "properties": {
                "experimentCondition": {
                    "description": "ExperimentCondition string 实验条件\n步骤对应的实验条件描述",
                    "type": "string",
                    "example": "实验条件"
                },
                "materialGroups": {
                    "description": "MaterialGroups []MaterialGroupData 材料组\n该步骤中涉及的材料组信息",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ai.MaterialGroupData"
                    }
                },
                "stepName": {
                    "description": "StepName string 步骤名称\n描述实验步骤的名称",
                    "type": "string",
                    "example": "步骤名称"
                }
            }
        },
        "ai.ForwardDirectionResponse": {
            "type": "object",
            "properties": {
                "aiResult": {
                    "description": "AiResult ForwardDirectionResult 数据\nai的结果",
                    "allOf": [
                        {
                            "$ref": "#/definitions/ai.ForwardDirectionResult"
                        }
                    ]
                },
                "historyList": {
                    "description": "historyList []ForwardDirectionResultInfo 数据\n实验记录的结果",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ai.ForwardDirectionResultInfo"
                    }
                }
            }
        },
        "ai.ForwardDirectionResult": {
            "type": "object",
            "properties": {
                "resultValue": {
                    "description": "ResultValue string 实验条件\n步骤对应的实验结果",
                    "type": "string",
                    "example": "步骤结果值"
                },
                "stepName": {
                    "description": "StepName string 步骤名称\n描述实验步骤的名称",
                    "type": "string",
                    "example": "步骤名称"
                }
            }
        },
        "ai.ForwardDirectionResultInfo": {
            "type": "object",
            "properties": {
                "experimentName": {
                    "description": "ExperimentName string 实验名称\n实验的名称信息",
                    "type": "string",
                    "example": "实验名称"
                },
                "resultValue": {
                    "description": "ResultValue string 实验条件\n步骤对应的实验结果",
                    "type": "string",
                    "example": "步骤结果值"
                },
                "stepName": {
                    "description": "StepName string 步骤名称\n描述实验步骤的名称",
                    "type": "string",
                    "example": "步骤名称"
                }
            }
        },
        "ai.MaterialData": {
            "type": "object",
            "properties": {
                "materialName": {
                    "description": "MaterialName string 材料名称\n材料的名称信息",
                    "type": "string",
                    "example": "材料名称"
                },
                "proportion": {
                    "description": "Proportion float64 材料占比\n材料在材料组中的占比，百分比形式",
                    "type": "number",
                    "example": 25.5
                }
            }
        },
        "ai.MaterialGroupData": {
            "type": "object",
            "properties": {
                "materialGroupName": {
                    "description": "MaterialGroupName string 材料组名称\n材料组的名称信息",
                    "type": "string",
                    "example": "材料组名称"
                },
                "materials": {
                    "description": "Materials []MaterialData 材料列表\n材料组内的具体材料信息",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ai.MaterialData"
                    }
                },
                "proportion": {
                    "description": "Proportion float64 材料组占比\n材料组在实验步骤中的占比，百分比形式",
                    "type": "number",
                    "example": 25.5
                }
            }
        },
        "auth.ChangePasswordRequest": {
            "type": "object",
            "required": [
                "confirmPassword",
                "identifier",
                "newPassword",
                "oldPassword"
            ],
            "properties": {
                "confirmPassword": {
                    "description": "ConfirmPassword 确认新密码，必填，必须与新密码一致",
                    "type": "string",
                    "example": "newpassword123"
                },
                "identifier": {
                    "description": "Identifier 用户标识（用户名|手机号|邮箱），必填，长度限制",
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 3,
                    "example": "user1@example.com"
                },
                "newPassword": {
                    "description": "NewPassword 新密码，必填，长度限制",
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 6,
                    "example": "newpassword123"
                },
                "oldPassword": {
                    "description": "OldPassword 旧密码，必填，长度限制",
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 6,
                    "example": "oldpassword123"
                }
            }
        },
        "auth.LoginRequest": {
            "type": "object",
            "required": [
                "identifier",
                "password"
            ],
            "properties": {
                "identifier": {
                    "description": "Identifier 用户标识（用户名|手机号|邮箱），必填，长度限制",
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 3,
                    "example": "user1@example.com"
                },
                "password": {
                    "description": "Password 密码，必填，长度限制",
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 6,
                    "example": "password123"
                }
            }
        },
        "auth.LoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "description": "Token 登陆凭证",
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzIwOTkwMTQsImlhdCI6MTczMjA5OTAxNCwidXNlcklkIjoiMmE1ZWVkNDItMjVhMy00MGJlLTlmY2QtNjEzMmJlYzgzNTE3In0.YyrvQS66uYNVtCKKi7rm7xqJrCIFSq12SXCJcqAxKso"
                }
            }
        },
        "data.ExperimentData": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "CreatedAt 创建时间\n格式为时间戳，创建时间",
                    "type": "string",
                    "example": "2006-01-02 15:04:05"
                },
                "endTime": {
                    "description": "EndTime 实验结束时间\n格式为时间戳，实验结束时间",
                    "type": "string",
                    "example": "2006-01-02 15:04:05"
                },
                "entryCategory": {
                    "description": "EntryCategory string 录入类别\nfile_import=文件导入, manual_entry=页面录入",
                    "type": "string",
                    "example": "1"
                },
                "experimentId": {
                    "description": "ExperimentID string 实验ID\n唯一标识实验的UUID",
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "experimentName": {
                    "description": "ExperimentName string 实验名称\n实验的名称信息",
                    "type": "string",
                    "example": "实验名称"
                },
                "experimenter": {
                    "description": "Experimenter string 实验者\n进行实验的人员名称",
                    "type": "string",
                    "example": "张三"
                },
                "startTime": {
                    "description": "StartTime 实验开始时间\n格式为时间戳，实验开始时间",
                    "type": "string",
                    "example": "2006-01-02 15:04:05"
                },
                "status": {
                    "description": "Status 实验状态\n表示实验的审核状态，包含 'pending_review'、'approved'、'rejected'",
                    "type": "string",
                    "example": "pending_review"
                },
                "userId": {
                    "description": "UserID string 操作用户ID\n记录操作该实验的用户 ID",
                    "type": "string",
                    "example": "987e6543-d21b-34c5-a654-123456789abc"
                },
                "username": {
                    "description": "Username 用户名\n表示实验相关的用户名",
                    "type": "string",
                    "example": "testuser"
                }
            }
        },
        "data.ExperimentDeleteRequest": {
            "type": "object",
            "properties": {
                "experimentId": {
                    "description": "experimentId 实验编号，必填，UUID格式\n唯一标识要删除的实验，格式必须为UUID4",
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                }
            }
        },
        "data.ExperimentInfoRequest": {
            "type": "object",
            "properties": {
                "experimentId": {
                    "description": "ExperimentID string 实验ID\n唯一标识实验的UUID",
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                }
            }
        },
        "data.ExperimentInfoResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "CreatedAt 创建时间\n格式为时间戳，创建时间",
                    "type": "string",
                    "example": "2006-01-02 15:04:05"
                },
                "endTime": {
                    "description": "EndTime 实验结束时间\n格式为时间戳，实验结束时间",
                    "type": "string",
                    "example": "2006-01-02 15:04:05"
                },
                "entryCategory": {
                    "description": "EntryCategory string 录入类别\nfile_import=文件导入, manual_entry=页面录入",
                    "type": "string",
                    "example": "1"
                },
                "experimentId": {
                    "description": "experimentId 实验编号，必填，UUID格式\n唯一标识要删除的实验，格式必须为UUID4",
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "experimentName": {
                    "description": "ExperimentName string 实验名称\n实验的名称信息",
                    "type": "string",
                    "example": "实验名称"
                },
                "experimenter": {
                    "description": "Experimenter string 实验者\n进行实验的人员名称",
                    "type": "string",
                    "example": "张三"
                },
                "materialGroups": {
                    "description": "MaterialGroups []MaterialGroupInfo 材料组\n该步骤中涉及的材料组信息",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/data.MaterialGroupInfo"
                    }
                },
                "startTime": {
                    "description": "StartTime 实验开始时间\n格式为时间戳，实验开始时间",
                    "type": "string",
                    "example": "2006-01-02 15:04:05"
                },
                "status": {
                    "description": "Status 实验状态\n表示实验的审核状态，包含 'pending_review'、'approved'、'rejected'",
                    "type": "string",
                    "example": "pending_review"
                },
                "stepInfo": {
                    "description": "StepInfo []ExperimentStepInfo 实验步骤数据\n该步骤中涉及的材料组信息",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/data.ExperimentStepInfo"
                    }
                },
                "userId": {
                    "description": "UserID string 操作用户ID\n记录操作该实验的用户 ID",
                    "type": "string",
                    "example": "987e6543-d21b-34c5-a654-123456789abc"
                },
                "username": {
                    "description": "Username 用户名\n表示实验相关的用户名",
                    "type": "string",
                    "example": "testuser"
                }
            }
        },
        "data.ExperimentListRequest": {
            "type": "object",
            "properties": {
                "endTime": {
                    "description": "EndTime string 结束时间\n创建时间，格式 2006-01-02 15:04:05",
                    "type": "string",
                    "example": "2006-01-02 15:04:05"
                },
                "experimentName": {
                    "description": "ExperimentName string 实验名称，选填，长度限制：2-128字符\n用于按名称模糊查询实验记录",
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 2,
                    "example": "实验名称"
                },
                "experimenter": {
                    "description": "Experimenter string 实验者，选填，长度限制：2-128字符\n进行实验的人员名称",
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 1,
                    "example": "张三"
                },
                "page": {
                    "description": "Page 页码，选填，范围限制：[1,10000]\n用于分页查询管理员列表，最小值为1，最大值为10000",
                    "type": "integer",
                    "maximum": 10000,
                    "minimum": 1,
                    "example": 1
                },
                "pageSize": {
                    "description": "PageSize 每页大小，选填，范围限制：[1,10000]\n用于限制每页返回的管理员数量，最小值为1，最大值为10000",
                    "type": "integer",
                    "maximum": 10000,
                    "minimum": 1,
                    "example": 10
                },
                "startTime": {
                    "description": "StartTime string 开始时间\n创建时间，格式 2006-01-02 15:04:05",
                    "type": "string",
                    "example": "2006-01-02 15:04:05"
                },
                "status": {
                    "description": "Status string 审核状态\n当前任务的处理状态，pending_review=待审核, approved=审核通过, rejected=审核不通过",
                    "type": "string",
                    "enum": [
                        "pending_review",
                        "approved",
                        "rejected"
                    ],
                    "example": "pending_review"
                },
                "taskId": {
                    "description": "TaskId string 任务id\n唯一标识实验的UUID",
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                }
            }
        },
        "data.ExperimentListResponse": {
            "type": "object",
            "properties": {
                "list": {
                    "description": "List []ExperimentData 数据\n分页返回的实验记录列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/data.ExperimentData"
                    }
                },
                "total": {
                    "description": "Total int64 总条数\n返回符合条件的实验记录总数",
                    "type": "integer",
                    "example": 100
                }
            }
        },
        "data.ExperimentStepInfo": {
            "type": "object",
            "properties": {
                "resultValue": {
                    "description": "ResultValue string 实验条件\n步骤对应的实验结果\nresin_mixing=树脂混合 {\"树脂粘度\":{\"温度\":27,\"粘度\":1350},\"环氧当量\":26}\nhardener_mixing=固化剂混合 {\"胺值\":9.5,\"固化剂粘度\":{\"温度\":27,\"粘度\":null}}\nresin_hardener_mixing=树脂/固化剂混合 {\"温度\":\"27℃\",\"可用时间\":140,\"混合粘度\":276}\nmechanical_performance=力学性能 {\"value\": 79}",
                    "type": "string",
                    "example": "步骤结果值"
                },
                "stepCategory": {
                    "description": "StepCategory 实验步骤类别\n实验步骤的类型，包含 'resin_mixing'、'hardener_mixing'、'resin_hardener_mixing'、'mechanical_performance'",
                    "type": "string",
                    "example": "resin_mixing"
                },
                "stepCondition": {
                    "description": "StepCondition string 实验条件\n步骤对应的实验条件描述",
                    "type": "string",
                    "example": "步骤实验条件"
                },
                "stepId": {
                    "description": "StepID string 步骤ID\n唯一标识实验步骤的UUID",
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174002"
                },
                "stepName": {
                    "description": "StepName string 步骤名称\n描述实验步骤的名称",
                    "type": "string",
                    "example": "步骤名称"
                }
            }
        },
        "data.MaterialGroupInfo": {
            "type": "object",
            "properties": {
                "materialGroupCategory": {
                    "description": "MaterialGroupCategory string 材料组类别\n材料组类别 resin=树脂, hardener=固化剂",
                    "type": "string",
                    "example": "材料组类别"
                },
                "materialGroupId": {
                    "description": "MaterialGroupID string 材料组ID\n唯一标识材料组的UUID",
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174003"
                },
                "materialGroupName": {
                    "description": "MaterialGroupName string 材料组名称\n材料组的名称信息",
                    "type": "string",
                    "example": "材料组名称"
                },
                "materials": {
                    "description": "Materials []MaterialInfo 材料列表\n材料组内的具体材料信息",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/data.MaterialInfo"
                    }
                },
                "parentId": {
                    "description": "MaterialGroupParentID string 材料组父级ID 顶级材料组为空\n唯一标识材料组父级的UUID",
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174003"
                },
                "proportion": {
                    "description": "Proportion float64 材料组占比\n材料组在实验步骤中的占比，百分比形式",
                    "type": "number",
                    "example": 25.5
                },
                "subGroups": {
                    "description": "SubGroups []MaterialGroupInfo 子材料组\n当前材料组包含的子材料组列表，支持层级嵌套",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/data.MaterialGroupInfo"
                    }
                }
            }
        },
        "data.MaterialInfo": {
            "type": "object",
            "properties": {
                "materialId": {
                    "description": "MaterialID string 材料ID\n唯一标识材料的UUID",
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174004"
                },
                "materialName": {
                    "description": "MaterialName string 材料名称\n材料的名称信息",
                    "type": "string",
                    "example": "材料名称"
                },
                "percentage": {
                    "description": "Percentage float64 材料占比\n材料在材料组中的占比，百分比形式",
                    "type": "number",
                    "example": 60
                }
            }
        },
        "data.TaskData": {
            "type": "object",
            "properties": {
                "aiFilePath": {
                    "description": "AiFilePath string ai处理后json文件路径\nAI 处理后的 JSON 文件存储路径",
                    "type": "string",
                    "example": "/uploads/2024/11/240628AI模型数据200组 含FRP性能-(对外）FD-ai.json"
                },
                "batchId": {
                    "description": "BatchID string 批次号\n用于标识一组相关任务的批次UUID",
                    "type": "string",
                    "example": "987e6543-e89b-12d3-a456-426614174001"
                },
                "createdAt": {
                    "description": "CreatedAt string 创建时间\n任务的创建时间，格式 2006-01-02 15:04:05",
                    "type": "string",
                    "example": "2006-01-02 15:04:05"
                },
                "fileName": {
                    "description": "FileName string 文件名称\n任务关联的文件名称",
                    "type": "string",
                    "example": "240628AI模型数据200组 含FRP性能-(对外）FD"
                },
                "filePath": {
                    "description": "FilePath string 文件路径\n存储文件的路径，指向文件在服务器上的位置",
                    "type": "string",
                    "example": "/uploads/2024/11/240628AI模型数据200组 含FRP性能-(对外）FD.json"
                },
                "jsonFilePath": {
                    "description": "JSONFilePath string 硬代码json文件路径\nJSON 文件存储的路径",
                    "type": "string",
                    "example": "/uploads/2024/11/240628AI模型数据200组 含FRP性能-(对外）FD.json"
                },
                "remark": {
                    "description": "Remark string 任务状态描述\n对任务状态的额外描述信息，如错误信息等",
                    "type": "string",
                    "example": "任务正在处理中"
                },
                "status": {
                    "description": "Status string 任务状态\n当前任务的处理状态，pending=待处理, processing=处理中, success=成功, failure=失败",
                    "type": "string",
                    "example": "pending"
                },
                "taskId": {
                    "description": "TaskID string 任务ID\n唯一标识任务的UUID",
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "updatedAt": {
                    "description": "UpdatedAt string 修改时间\n任务的最后更新时间，采用 ISO 8601 格式（例如：2024-11-18T12:00:00Z）",
                    "type": "string",
                    "example": "2024-11-18T12:00:00Z"
                }
            }
        },
        "data.TaskListRequest": {
            "type": "object",
            "properties": {
                "endTime": {
                    "description": "EndTime string 结束时间\n任务的创建时间，格式 2006-01-02 15:04:05",
                    "type": "string",
                    "example": "2006-01-02 15:04:05"
                },
                "fileName": {
                    "description": "FileName string 文件名称，选填，长度限制：2-128字符\n用于按文件名称模糊查询任务记录",
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 2,
                    "example": "文件名称"
                },
                "page": {
                    "description": "Page 页码，选填，范围限制：[1,10000]\n用于分页查询管理员列表，最小值为1，最大值为10000",
                    "type": "integer",
                    "maximum": 10000,
                    "minimum": 1,
                    "example": 1
                },
                "pageSize": {
                    "description": "PageSize 每页大小，选填，范围限制：[1,10000]\n用于限制每页返回的管理员数量，最小值为1，最大值为10000",
                    "type": "integer",
                    "maximum": 10000,
                    "minimum": 1,
                    "example": 10
                },
                "startTime": {
                    "description": "StartTime string 开始时间\n任务的创建时间，格式 2006-01-02 15:04:05",
                    "type": "string",
                    "example": "2006-01-02 15:04:05"
                },
                "status": {
                    "description": "Status string 任务状态\n当前任务的处理状态，pending=待处理, processing=处理中, success=成功, failure=失败",
                    "type": "string",
                    "enum": [
                        "pending",
                        "processing",
                        "success",
                        "failure"
                    ],
                    "example": "pending"
                }
            }
        },
        "data.TaskListResponse": {
            "type": "object",
            "properties": {
                "list": {
                    "description": "List []TaskData 数据\n分页返回的任务记录列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/data.TaskData"
                    }
                },
                "total": {
                    "description": "Total int64 总条数\n返回符合条件的任务记录总数",
                    "type": "integer",
                    "example": 100
                }
            }
        },
        "dto.Empty": {
            "type": "object"
        },
        "dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "错误码",
                    "type": "integer"
                },
                "message": {
                    "description": "错误信息",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
