definitions:
  auth.ChangePasswordRequest:
    properties:
      confirmPassword:
        description: ConfirmPassword 确认新密码，必填，必须与新密码一致
        example: newpassword123
        type: string
      identifier:
        description: Identifier 用户标识（用户名|手机号|邮箱），必填，长度限制
        example: user1@example.com
        maxLength: 128
        minLength: 3
        type: string
      newPassword:
        description: NewPassword 新密码，必填，长度限制
        example: newpassword123
        maxLength: 32
        minLength: 6
        type: string
      oldPassword:
        description: OldPassword 旧密码，必填，长度限制
        example: oldpassword123
        maxLength: 32
        minLength: 6
        type: string
    required:
    - confirmPassword
    - identifier
    - newPassword
    - oldPassword
    type: object
  auth.LoginRequest:
    properties:
      identifier:
        description: Identifier 用户标识（用户名|手机号|邮箱），必填，长度限制
        example: user1@example.com
        maxLength: 128
        minLength: 3
        type: string
      password:
        description: Password 密码，必填，长度限制
        example: password123
        maxLength: 32
        minLength: 6
        type: string
    required:
    - identifier
    - password
    type: object
  auth.LoginResponse:
    properties:
      token:
        description: Token 登陆凭证
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzIwOTkwMTQsImlhdCI6MTczMjA5OTAxNCwidXNlcklkIjoiMmE1ZWVkNDItMjVhMy00MGJlLTlmY2QtNjEzMmJlYzgzNTE3In0.YyrvQS66uYNVtCKKi7rm7xqJrCIFSq12SXCJcqAxKso
        type: string
    type: object
  dto.Empty:
    type: object
  dto.ErrorResponse:
    properties:
      code:
        description: 错误码
        type: integer
      message:
        description: 错误信息
        type: string
    type: object
info:
  contact: {}
paths:
  /changPassword:
    put:
      consumes:
      - application/json
      description: 根据提供的原密码及新密码等信息修改用户当前账户的密码
      parameters:
      - description: 请求参数，包含原密码、新密码等修改密码所需信息
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/auth.ChangePasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功修改密码，返回空对象表示操作成功
          schema:
            $ref: '#/definitions/dto.Empty'
        "201":
          description: 可根据实际情况设置不同成功状态码及对应含义，这里示例201可表示密码已成功更新并生效
          schema:
            $ref: '#/definitions/dto.Empty'
        "400":
          description: 请求参数错误，如原密码错误、新密码格式不符合要求等
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 服务器内部错误，可能是数据库更新出错、验证逻辑异常等情况
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 修改用户密码
      tags:
      - 用户认证
  /login:
    post:
      consumes:
      - application/json
      description: 提供用户名和密码进行登录操作，验证用户身份并获取相应权限
      parameters:
      - description: 请求参数，包含用户名、密码等登录所需信息
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/auth.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功登录，返回token凭证表示操作成功
          schema:
            $ref: '#/definitions/auth.LoginResponse'
        "400":
          description: 请求参数错误，如用户名或密码格式不正确等
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: 服务器内部错误，可能是数据库查询出错、验证逻辑异常等情况
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: 用户登录
      tags:
      - 用户认证
swagger: "2.0"
